### 帮助文档 https://segmentfault.com/a/1190000016300254
### 变量
@host = http://localhost:8080
@json = Content-Type: application/json
@form = application/x-www-form-urlencoded

### 查询用户
GET {{host}}/api/users/3

### 插入用户
POST {{host}}/api/users
Content-Type: application/x-www-form-urlencoded

userId=8&username=Eight
